services:
  backend:
    depends_on:
      - 'database'
    build:
      context: ./
      dockerfile: ./backend.Dockerfile
  database: 
    image: postgres:12-bullseye
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
