on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: backend
          tags: lastest ${{ github.sha }}
          containerfiles: |
            ./backend.Dockerfile

      # - name: Set up Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.20'
          
      # - name: Download dependencies
      #   run: go get .
      #   working-directory: ./cmd

      # - name: Build
      #   run: go build -o ./server.out .
      #   working-directory: ./cmd
        
