on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: backend
      IMAGE_TAGS: v1 ${{ github.sha }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ github.token }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          containerfiles: |
            ./backend.Dockerfile

      - name: Push To GHCR
        uses: ./
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"

      # - name: Set up Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.20'
          
      # - name: Download dependencies
      #   run: go get .
      #   working-directory: ./cmd

      # - name: Build
      #   run: go build -o ./server.out .
      #   working-directory: ./cmd
        
